using CliFx;
using CliFx.Attributes;
using CliFx.Infrastructure;

namespace NetGenBox.CLI;

[Command("netgen")]
public class NetListCommand : ICommand
{

    [CommandOption("path", 'p', Description = "Path of EDIF netlist file generated by Xilinx, usually *.ndf")]
    public required string EdifPath { get; set; }

    [CommandOption("output", 'o',Description = "Output path to write generated verilog file", IsRequired = false)]
    public string? OutputPath { get; set; }
    
    public ValueTask ExecuteAsync(IConsole console)
    {
        
        return default;
    }
}